/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TurretData = IDL.Record({
  'id' : IDL.Text,
  'level' : IDL.Nat,
  'experience' : IDL.Nat,
  'kills' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GifMetadata = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const AvatarType = IDL.Variant({
  'custom' : IDL.Record({ 'blob' : ExternalBlob, 'fileType' : IDL.Text }),
  'preset' : IDL.Nat,
});
export const PuffinProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarType' : AvatarType,
});
export const GameMode = IDL.Variant({
  'flightAdventure' : IDL.Null,
  'puffinSlide' : IDL.Null,
  'puffinTowerDefense' : IDL.Null,
  'fishFrenzy' : IDL.Null,
  'puffinColonyWars' : IDL.Null,
  'puffinRescue' : IDL.Null,
  'arcticSurf' : IDL.Null,
  'puffinCatch' : IDL.Null,
});
export const ScoreEntry = IDL.Record({
  'principal' : IDL.Opt(IDL.Principal),
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});
export const RewardHistory = IDL.Record({
  'blockIndex' : IDL.Nat,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimRewards' : IDL.Func(
      [],
      [IDL.Record({ 'blockIndex' : IDL.Nat, 'amount' : IDL.Nat })],
      [],
    ),
  'deleteCallerGif' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'deleted' : IDL.Bool })],
      [],
    ),
  'getAccountID' : IDL.Func([], [IDL.Text], ['query']),
  'getAllColonyWarsStats' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Principal,
            IDL.Record({
              'totalResourcesEarned' : IDL.Nat,
              'totalTurretKills' : IDL.Nat,
              'turrets' : IDL.Vec(IDL.Tuple(IDL.Text, TurretData)),
              'totalGames' : IDL.Nat,
            }),
          )
        ),
      ],
      ['query'],
    ),
  'getAllGifs' : IDL.Func([], [IDL.Vec(GifMetadata)], ['query']),
  'getAvatar' : IDL.Func([AvatarType], [IDL.Opt(IDL.Vec(IDL.Nat8))], ['query']),
  'getCallerPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PuffinProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getColonyWarsStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'totalResourcesEarned' : IDL.Nat,
            'totalTurretKills' : IDL.Nat,
            'turrets' : IDL.Vec(IDL.Tuple(IDL.Text, TurretData)),
            'totalGames' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getDailyRewardStats' : IDL.Func(
      [IDL.Int],
      [
        IDL.Opt(
          IDL.Record({
            'totalRewardsSent' : IDL.Nat,
            'userRewardsSent' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
            'usersClaimed' : IDL.Vec(IDL.Principal),
            'timestamp' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getGif' : IDL.Func([IDL.Text], [IDL.Opt(GifMetadata)], ['query']),
  'getICPBalance' : IDL.Func([], [IDL.Nat], []),
  'getLeaderboard' : IDL.Func([GameMode], [IDL.Vec(ScoreEntry)], ['query']),
  'getPersonalStats' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'flightAdventure' : IDL.Opt(IDL.Nat),
            'puffinSlide' : IDL.Opt(IDL.Nat),
            'puffinTowerDefense' : IDL.Opt(IDL.Nat),
            'fishFrenzy' : IDL.Opt(IDL.Nat),
            'puffinColonyWars' : IDL.Opt(IDL.Nat),
            'puffinRescue' : IDL.Opt(IDL.Nat),
            'arcticSurf' : IDL.Opt(IDL.Nat),
            'puffinCatch' : IDL.Opt(IDL.Nat),
          })
        ),
      ],
      ['query'],
    ),
  'getPlayerRewardStatus' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'claimedHistory' : IDL.Vec(RewardHistory),
            'unclaimedWins' : IDL.Nat,
            'totalWins' : IDL.Nat,
            'unclaimedAmount' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getPresetAvatar' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  'getPuffinBalance' : IDL.Func([], [IDL.Nat], []),
  'getRecentRecipients' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRewardHistory' : IDL.Func([], [IDL.Vec(RewardHistory)], ['query']),
  'getTurretData' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(TurretData)],
      ['query'],
    ),
  'getUnclaimedRewards' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PuffinProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeholderChatResponse' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'recordGameEnd' : IDL.Func([], [], []),
  'recordTurretExperience' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'recordTurretKill' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([PuffinProfile], [], []),
  'sendICPTryAccountId' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'sendPuffin' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
  'submitScore' : IDL.Func([GameMode, IDL.Text, IDL.Nat], [], []),
  'upgradeTurret' : IDL.Func([IDL.Text], [], []),
  'uploadCustomAvatar' : IDL.Func([ExternalBlob, IDL.Text], [AvatarType], []),
  'uploadGif' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TurretData = IDL.Record({
    'id' : IDL.Text,
    'level' : IDL.Nat,
    'experience' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GifMetadata = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const AvatarType = IDL.Variant({
    'custom' : IDL.Record({ 'blob' : ExternalBlob, 'fileType' : IDL.Text }),
    'preset' : IDL.Nat,
  });
  const PuffinProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarType' : AvatarType,
  });
  const GameMode = IDL.Variant({
    'flightAdventure' : IDL.Null,
    'puffinSlide' : IDL.Null,
    'puffinTowerDefense' : IDL.Null,
    'fishFrenzy' : IDL.Null,
    'puffinColonyWars' : IDL.Null,
    'puffinRescue' : IDL.Null,
    'arcticSurf' : IDL.Null,
    'puffinCatch' : IDL.Null,
  });
  const ScoreEntry = IDL.Record({
    'principal' : IDL.Opt(IDL.Principal),
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  const RewardHistory = IDL.Record({
    'blockIndex' : IDL.Nat,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimRewards' : IDL.Func(
        [],
        [IDL.Record({ 'blockIndex' : IDL.Nat, 'amount' : IDL.Nat })],
        [],
      ),
    'deleteCallerGif' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'deleted' : IDL.Bool })],
        [],
      ),
    'getAccountID' : IDL.Func([], [IDL.Text], ['query']),
    'getAllColonyWarsStats' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              IDL.Record({
                'totalResourcesEarned' : IDL.Nat,
                'totalTurretKills' : IDL.Nat,
                'turrets' : IDL.Vec(IDL.Tuple(IDL.Text, TurretData)),
                'totalGames' : IDL.Nat,
              }),
            )
          ),
        ],
        ['query'],
      ),
    'getAllGifs' : IDL.Func([], [IDL.Vec(GifMetadata)], ['query']),
    'getAvatar' : IDL.Func(
        [AvatarType],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getCallerPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(PuffinProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getColonyWarsStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'totalResourcesEarned' : IDL.Nat,
              'totalTurretKills' : IDL.Nat,
              'turrets' : IDL.Vec(IDL.Tuple(IDL.Text, TurretData)),
              'totalGames' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getDailyRewardStats' : IDL.Func(
        [IDL.Int],
        [
          IDL.Opt(
            IDL.Record({
              'totalRewardsSent' : IDL.Nat,
              'userRewardsSent' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
              'usersClaimed' : IDL.Vec(IDL.Principal),
              'timestamp' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getGif' : IDL.Func([IDL.Text], [IDL.Opt(GifMetadata)], ['query']),
    'getICPBalance' : IDL.Func([], [IDL.Nat], []),
    'getLeaderboard' : IDL.Func([GameMode], [IDL.Vec(ScoreEntry)], ['query']),
    'getPersonalStats' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'flightAdventure' : IDL.Opt(IDL.Nat),
              'puffinSlide' : IDL.Opt(IDL.Nat),
              'puffinTowerDefense' : IDL.Opt(IDL.Nat),
              'fishFrenzy' : IDL.Opt(IDL.Nat),
              'puffinColonyWars' : IDL.Opt(IDL.Nat),
              'puffinRescue' : IDL.Opt(IDL.Nat),
              'arcticSurf' : IDL.Opt(IDL.Nat),
              'puffinCatch' : IDL.Opt(IDL.Nat),
            })
          ),
        ],
        ['query'],
      ),
    'getPlayerRewardStatus' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'claimedHistory' : IDL.Vec(RewardHistory),
              'unclaimedWins' : IDL.Nat,
              'totalWins' : IDL.Nat,
              'unclaimedAmount' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getPresetAvatar' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    'getPuffinBalance' : IDL.Func([], [IDL.Nat], []),
    'getRecentRecipients' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRewardHistory' : IDL.Func([], [IDL.Vec(RewardHistory)], ['query']),
    'getTurretData' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(TurretData)],
        ['query'],
      ),
    'getUnclaimedRewards' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PuffinProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeholderChatResponse' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'recordGameEnd' : IDL.Func([], [], []),
    'recordTurretExperience' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'recordTurretKill' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([PuffinProfile], [], []),
    'sendICPTryAccountId' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'sendPuffin' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Nat], []),
    'submitScore' : IDL.Func([GameMode, IDL.Text, IDL.Nat], [], []),
    'upgradeTurret' : IDL.Func([IDL.Text], [], []),
    'uploadCustomAvatar' : IDL.Func([ExternalBlob, IDL.Text], [AvatarType], []),
    'uploadGif' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };