/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvatarType = {
    'custom' : { 'blob' : ExternalBlob, 'fileType' : string }
  } |
  { 'preset' : bigint };
export type ExternalBlob = Uint8Array;
export type GameMode = { 'flightAdventure' : null } |
  { 'puffinSlide' : null } |
  { 'puffinTowerDefense' : null } |
  { 'fishFrenzy' : null } |
  { 'puffinColonyWars' : null } |
  { 'puffinRescue' : null } |
  { 'arcticSurf' : null } |
  { 'puffinCatch' : null };
export interface GifMetadata {
  'id' : string,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
  'description' : string,
}
export interface PuffinProfile {
  'bio' : string,
  'displayName' : string,
  'avatarType' : AvatarType,
}
export interface RewardHistory {
  'blockIndex' : bigint,
  'timestamp' : bigint,
  'amount' : bigint,
}
export interface ScoreEntry {
  'principal' : [] | [Principal],
  'score' : bigint,
  'playerName' : string,
}
export interface TurretData {
  'id' : string,
  'level' : bigint,
  'experience' : bigint,
  'kills' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimRewards' : ActorMethod<
    [],
    { 'blockIndex' : bigint, 'amount' : bigint }
  >,
  'deleteCallerGif' : ActorMethod<[string], { 'deleted' : boolean }>,
  'getAccountID' : ActorMethod<[], string>,
  'getAllColonyWarsStats' : ActorMethod<
    [],
    Array<
      [
        Principal,
        {
          'totalResourcesEarned' : bigint,
          'totalTurretKills' : bigint,
          'turrets' : Array<[string, TurretData]>,
          'totalGames' : bigint,
        },
      ]
    >
  >,
  'getAllGifs' : ActorMethod<[], Array<GifMetadata>>,
  'getAvatar' : ActorMethod<[AvatarType], [] | [Uint8Array]>,
  'getCallerPrincipal' : ActorMethod<[], Principal>,
  'getCallerUserProfile' : ActorMethod<[], [] | [PuffinProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getColonyWarsStats' : ActorMethod<
    [Principal],
    [] | [
      {
        'totalResourcesEarned' : bigint,
        'totalTurretKills' : bigint,
        'turrets' : Array<[string, TurretData]>,
        'totalGames' : bigint,
      }
    ]
  >,
  'getDailyRewardStats' : ActorMethod<
    [bigint],
    [] | [
      {
        'totalRewardsSent' : bigint,
        'userRewardsSent' : Array<[Principal, bigint]>,
        'usersClaimed' : Array<Principal>,
        'timestamp' : bigint,
      }
    ]
  >,
  'getGif' : ActorMethod<[string], [] | [GifMetadata]>,
  'getICPBalance' : ActorMethod<[], bigint>,
  'getLeaderboard' : ActorMethod<[GameMode], Array<ScoreEntry>>,
  'getPersonalStats' : ActorMethod<
    [Principal],
    [] | [
      {
        'flightAdventure' : [] | [bigint],
        'puffinSlide' : [] | [bigint],
        'puffinTowerDefense' : [] | [bigint],
        'fishFrenzy' : [] | [bigint],
        'puffinColonyWars' : [] | [bigint],
        'puffinRescue' : [] | [bigint],
        'arcticSurf' : [] | [bigint],
        'puffinCatch' : [] | [bigint],
      }
    ]
  >,
  'getPlayerRewardStatus' : ActorMethod<
    [Principal],
    [] | [
      {
        'claimedHistory' : Array<RewardHistory>,
        'unclaimedWins' : bigint,
        'totalWins' : bigint,
        'unclaimedAmount' : bigint,
      }
    ]
  >,
  'getPresetAvatar' : ActorMethod<[bigint], [] | [Uint8Array]>,
  'getPuffinBalance' : ActorMethod<[], bigint>,
  'getRecentRecipients' : ActorMethod<[], Array<string>>,
  'getRewardHistory' : ActorMethod<[], Array<RewardHistory>>,
  'getTurretData' : ActorMethod<[Principal, string], [] | [TurretData]>,
  'getUnclaimedRewards' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PuffinProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeholderChatResponse' : ActorMethod<[string], string>,
  'recordGameEnd' : ActorMethod<[], undefined>,
  'recordTurretExperience' : ActorMethod<[string, bigint], undefined>,
  'recordTurretKill' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[PuffinProfile], undefined>,
  'sendICPTryAccountId' : ActorMethod<[string, bigint], bigint>,
  'sendPuffin' : ActorMethod<[Principal, bigint], bigint>,
  'submitScore' : ActorMethod<[GameMode, string, bigint], undefined>,
  'upgradeTurret' : ActorMethod<[string], undefined>,
  'uploadCustomAvatar' : ActorMethod<[ExternalBlob, string], AvatarType>,
  'uploadGif' : ActorMethod<[string, string, string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];