/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GifMetadata {
    id: string;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
    description: string;
}
export interface ScoreEntry {
    principal?: Principal;
    score: bigint;
    playerName: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type AvatarType = {
    __kind__: "custom";
    custom: {
        blob: ExternalBlob;
        fileType: string;
    };
} | {
    __kind__: "preset";
    preset: bigint;
};
export interface RewardHistory {
    blockIndex: bigint;
    timestamp: bigint;
    amount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TurretData {
    id: string;
    level: bigint;
    experience: bigint;
    kills: bigint;
}
export interface PuffinProfile {
    bio: string;
    displayName: string;
    avatarType: AvatarType;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum GameMode {
    flightAdventure = "flightAdventure",
    puffinSlide = "puffinSlide",
    puffinTowerDefense = "puffinTowerDefense",
    fishFrenzy = "fishFrenzy",
    puffinColonyWars = "puffinColonyWars",
    puffinRescue = "puffinRescue",
    arcticSurf = "arcticSurf",
    puffinCatch = "puffinCatch"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimRewards(): Promise<{
        blockIndex: bigint;
        amount: bigint;
    }>;
    deleteCallerGif(id: string): Promise<{
        deleted: boolean;
    }>;
    getAccountID(): Promise<string>;
    getAllColonyWarsStats(): Promise<Array<[Principal, {
            totalResourcesEarned: bigint;
            totalTurretKills: bigint;
            turrets: Array<[string, TurretData]>;
            totalGames: bigint;
        }]>>;
    getAllGifs(): Promise<Array<GifMetadata>>;
    getAvatar(avatarType: AvatarType): Promise<Uint8Array | null>;
    getCallerPrincipal(): Promise<Principal>;
    getCallerUserProfile(): Promise<PuffinProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getColonyWarsStats(playerId: Principal): Promise<{
        totalResourcesEarned: bigint;
        totalTurretKills: bigint;
        turrets: Array<[string, TurretData]>;
        totalGames: bigint;
    } | null>;
    getDailyRewardStats(day: bigint): Promise<{
        totalRewardsSent: bigint;
        userRewardsSent: Array<[Principal, bigint]>;
        usersClaimed: Array<Principal>;
        timestamp: bigint;
    } | null>;
    getGif(id: string): Promise<GifMetadata | null>;
    getICPBalance(): Promise<bigint>;
    getLeaderboard(gameMode: GameMode): Promise<Array<ScoreEntry>>;
    getPersonalStats(principal: Principal): Promise<{
        flightAdventure?: bigint;
        puffinSlide?: bigint;
        puffinTowerDefense?: bigint;
        fishFrenzy?: bigint;
        puffinColonyWars?: bigint;
        puffinRescue?: bigint;
        arcticSurf?: bigint;
        puffinCatch?: bigint;
    } | null>;
    getPlayerRewardStatus(player: Principal): Promise<{
        claimedHistory: Array<RewardHistory>;
        unclaimedWins: bigint;
        totalWins: bigint;
        unclaimedAmount: bigint;
    } | null>;
    getPresetAvatar(index: bigint): Promise<Uint8Array | null>;
    getPuffinBalance(): Promise<bigint>;
    getRecentRecipients(): Promise<Array<string>>;
    getRewardHistory(): Promise<Array<RewardHistory>>;
    getTurretData(playerId: Principal, turretId: string): Promise<TurretData | null>;
    getUnclaimedRewards(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<PuffinProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    placeholderChatResponse(_prompt: string): Promise<string>;
    recordGameEnd(): Promise<void>;
    recordTurretExperience(turretId: string, experience: bigint): Promise<void>;
    recordTurretKill(turretId: string, resourcesEarned: bigint): Promise<void>;
    saveCallerUserProfile(profile: PuffinProfile): Promise<void>;
    sendICPTryAccountId(to: string, amount: bigint): Promise<bigint>;
    sendPuffin(to: Principal, amount: bigint): Promise<bigint>;
    submitScore(gameMode: GameMode, playerName: string, score: bigint): Promise<void>;
    upgradeTurret(turretId: string): Promise<void>;
    uploadCustomAvatar(blob: ExternalBlob, fileType: string): Promise<AvatarType>;
    uploadGif(id: string, name: string, description: string, blob: ExternalBlob): Promise<void>;
}
import type { AvatarType as _AvatarType, ExternalBlob as _ExternalBlob, GameMode as _GameMode, GifMetadata as _GifMetadata, PuffinProfile as _PuffinProfile, RewardHistory as _RewardHistory, ScoreEntry as _ScoreEntry, TurretData as _TurretData, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async claimRewards(): Promise<{
        blockIndex: bigint;
        amount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.claimRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimRewards();
            return result;
        }
    }
    async deleteCallerGif(arg0: string): Promise<{
        deleted: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallerGif(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallerGif(arg0);
            return result;
        }
    }
    async getAccountID(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountID();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountID();
            return result;
        }
    }
    async getAllColonyWarsStats(): Promise<Array<[Principal, {
            totalResourcesEarned: bigint;
            totalTurretKills: bigint;
            turrets: Array<[string, TurretData]>;
            totalGames: bigint;
        }]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllColonyWarsStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllColonyWarsStats();
            return result;
        }
    }
    async getAllGifs(): Promise<Array<GifMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGifs();
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGifs();
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAvatar(arg0: AvatarType): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvatar(await to_candid_AvatarType_n14(this.uploadFile, this.downloadFile, arg0));
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvatar(await to_candid_AvatarType_n14(this.uploadFile, this.downloadFile, arg0));
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerPrincipal(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPrincipal();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<PuffinProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getColonyWarsStats(arg0: Principal): Promise<{
        totalResourcesEarned: bigint;
        totalTurretKills: bigint;
        turrets: Array<[string, TurretData]>;
        totalGames: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getColonyWarsStats(arg0);
                return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColonyWarsStats(arg0);
            return from_candid_opt_n27(this.uploadFile, this.downloadFile, result);
        }
    }
    async getDailyRewardStats(arg0: bigint): Promise<{
        totalRewardsSent: bigint;
        userRewardsSent: Array<[Principal, bigint]>;
        usersClaimed: Array<Principal>;
        timestamp: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRewardStats(arg0);
                return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRewardStats(arg0);
            return from_candid_opt_n28(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGif(arg0: string): Promise<GifMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGif(arg0);
                return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGif(arg0);
            return from_candid_opt_n29(this.uploadFile, this.downloadFile, result);
        }
    }
    async getICPBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getICPBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICPBalance();
            return result;
        }
    }
    async getLeaderboard(arg0: GameMode): Promise<Array<ScoreEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(to_candid_GameMode_n30(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n32(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(to_candid_GameMode_n30(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n32(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPersonalStats(arg0: Principal): Promise<{
        flightAdventure?: bigint;
        puffinSlide?: bigint;
        puffinTowerDefense?: bigint;
        fishFrenzy?: bigint;
        puffinColonyWars?: bigint;
        puffinRescue?: bigint;
        arcticSurf?: bigint;
        puffinCatch?: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPersonalStats(arg0);
                return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPersonalStats(arg0);
            return from_candid_opt_n36(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPlayerRewardStatus(arg0: Principal): Promise<{
        claimedHistory: Array<RewardHistory>;
        unclaimedWins: bigint;
        totalWins: bigint;
        unclaimedAmount: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerRewardStatus(arg0);
                return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerRewardStatus(arg0);
            return from_candid_opt_n38(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPresetAvatar(arg0: bigint): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresetAvatar(arg0);
                return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresetAvatar(arg0);
            return from_candid_opt_n18(this.uploadFile, this.downloadFile, result);
        }
    }
    async getPuffinBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPuffinBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPuffinBalance();
            return result;
        }
    }
    async getRecentRecipients(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentRecipients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentRecipients();
            return result;
        }
    }
    async getRewardHistory(): Promise<Array<RewardHistory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardHistory();
            return result;
        }
    }
    async getTurretData(arg0: Principal, arg1: string): Promise<TurretData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTurretData(arg0, arg1);
                return from_candid_opt_n39(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTurretData(arg0, arg1);
            return from_candid_opt_n39(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUnclaimedRewards(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnclaimedRewards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnclaimedRewards();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<PuffinProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeholderChatResponse(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.placeholderChatResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeholderChatResponse(arg0);
            return result;
        }
    }
    async recordGameEnd(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordGameEnd();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordGameEnd();
            return result;
        }
    }
    async recordTurretExperience(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTurretExperience(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTurretExperience(arg0, arg1);
            return result;
        }
    }
    async recordTurretKill(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTurretKill(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTurretKill(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: PuffinProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_PuffinProfile_n40(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_PuffinProfile_n40(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async sendICPTryAccountId(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendICPTryAccountId(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendICPTryAccountId(arg0, arg1);
            return result;
        }
    }
    async sendPuffin(arg0: Principal, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendPuffin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendPuffin(arg0, arg1);
            return result;
        }
    }
    async submitScore(arg0: GameMode, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScore(to_candid_GameMode_n30(this.uploadFile, this.downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScore(to_candid_GameMode_n30(this.uploadFile, this.downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async upgradeTurret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeTurret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeTurret(arg0);
            return result;
        }
    }
    async uploadCustomAvatar(arg0: ExternalBlob, arg1: string): Promise<AvatarType> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadCustomAvatar(await to_candid_ExternalBlob_n17(this.uploadFile, this.downloadFile, arg0), arg1);
                return from_candid_AvatarType_n22(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadCustomAvatar(await to_candid_ExternalBlob_n17(this.uploadFile, this.downloadFile, arg0), arg1);
            return from_candid_AvatarType_n22(this.uploadFile, this.downloadFile, result);
        }
    }
    async uploadGif(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadGif(arg0, arg1, arg2, await to_candid_ExternalBlob_n17(this.uploadFile, this.downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadGif(arg0, arg1, arg2, await to_candid_ExternalBlob_n17(this.uploadFile, this.downloadFile, arg3));
            return result;
        }
    }
}
async function from_candid_AvatarType_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvatarType): Promise<AvatarType> {
    return await from_candid_variant_n23(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_GifMetadata_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GifMetadata): Promise<GifMetadata> {
    return await from_candid_record_n12(uploadFile, downloadFile, value);
}
async function from_candid_PuffinProfile_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PuffinProfile): Promise<PuffinProfile> {
    return await from_candid_record_n21(uploadFile, downloadFile, value);
}
function from_candid_ScoreEntry_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScoreEntry): ScoreEntry {
    return from_candid_record_n34(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PuffinProfile]): Promise<PuffinProfile | null> {
    return value.length === 0 ? null : await from_candid_PuffinProfile_n20(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        totalResourcesEarned: bigint;
        totalTurretKills: bigint;
        turrets: Array<[string, _TurretData]>;
        totalGames: bigint;
    }]): {
    totalResourcesEarned: bigint;
    totalTurretKills: bigint;
    turrets: Array<[string, TurretData]>;
    totalGames: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        totalRewardsSent: bigint;
        userRewardsSent: Array<[Principal, bigint]>;
        usersClaimed: Array<Principal>;
        timestamp: bigint;
    }]): {
    totalRewardsSent: bigint;
    userRewardsSent: Array<[Principal, bigint]>;
    usersClaimed: Array<Principal>;
    timestamp: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GifMetadata]): Promise<GifMetadata | null> {
    return value.length === 0 ? null : await from_candid_GifMetadata_n11(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        flightAdventure: [] | [bigint];
        puffinSlide: [] | [bigint];
        puffinTowerDefense: [] | [bigint];
        fishFrenzy: [] | [bigint];
        puffinColonyWars: [] | [bigint];
        puffinRescue: [] | [bigint];
        arcticSurf: [] | [bigint];
        puffinCatch: [] | [bigint];
    }]): {
    flightAdventure?: bigint;
    puffinSlide?: bigint;
    puffinTowerDefense?: bigint;
    fishFrenzy?: bigint;
    puffinColonyWars?: bigint;
    puffinRescue?: bigint;
    arcticSurf?: bigint;
    puffinCatch?: bigint;
} | null {
    return value.length === 0 ? null : from_candid_record_n37(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        claimedHistory: Array<_RewardHistory>;
        unclaimedWins: bigint;
        totalWins: bigint;
        unclaimedAmount: bigint;
    }]): {
    claimedHistory: Array<RewardHistory>;
    unclaimedWins: bigint;
    totalWins: bigint;
    unclaimedAmount: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TurretData]): TurretData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    blob: _ExternalBlob;
    name: string;
    description: string;
}): Promise<{
    id: string;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
    description: string;
}> {
    return {
        id: value.id,
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n13(uploadFile, downloadFile, value.blob),
        name: value.name,
        description: value.description
    };
}
async function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    avatarType: _AvatarType;
}): Promise<{
    bio: string;
    displayName: string;
    avatarType: AvatarType;
}> {
    return {
        bio: value.bio,
        displayName: value.displayName,
        avatarType: await from_candid_AvatarType_n22(uploadFile, downloadFile, value.avatarType)
    };
}
async function from_candid_record_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    fileType: string;
}): Promise<{
    blob: ExternalBlob;
    fileType: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n13(uploadFile, downloadFile, value.blob),
        fileType: value.fileType
    };
}
function from_candid_record_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: [] | [Principal];
    score: bigint;
    playerName: string;
}): {
    principal?: Principal;
    score: bigint;
    playerName: string;
} {
    return {
        principal: record_opt_to_undefined(from_candid_opt_n35(uploadFile, downloadFile, value.principal)),
        score: value.score,
        playerName: value.playerName
    };
}
function from_candid_record_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flightAdventure: [] | [bigint];
    puffinSlide: [] | [bigint];
    puffinTowerDefense: [] | [bigint];
    fishFrenzy: [] | [bigint];
    puffinColonyWars: [] | [bigint];
    puffinRescue: [] | [bigint];
    arcticSurf: [] | [bigint];
    puffinCatch: [] | [bigint];
}): {
    flightAdventure?: bigint;
    puffinSlide?: bigint;
    puffinTowerDefense?: bigint;
    fishFrenzy?: bigint;
    puffinColonyWars?: bigint;
    puffinRescue?: bigint;
    arcticSurf?: bigint;
    puffinCatch?: bigint;
} {
    return {
        flightAdventure: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.flightAdventure)),
        puffinSlide: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.puffinSlide)),
        puffinTowerDefense: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.puffinTowerDefense)),
        fishFrenzy: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.fishFrenzy)),
        puffinColonyWars: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.puffinColonyWars)),
        puffinRescue: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.puffinRescue)),
        arcticSurf: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.arcticSurf)),
        puffinCatch: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.puffinCatch))
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
async function from_candid_variant_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: {
        blob: _ExternalBlob;
        fileType: string;
    };
} | {
    preset: bigint;
}): Promise<{
    __kind__: "custom";
    custom: {
        blob: ExternalBlob;
        fileType: string;
    };
} | {
    __kind__: "preset";
    preset: bigint;
}> {
    return "custom" in value ? {
        __kind__: "custom",
        custom: await from_candid_record_n24(uploadFile, downloadFile, value.custom)
    } : "preset" in value ? {
        __kind__: "preset",
        preset: value.preset
    } : value;
}
function from_candid_variant_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GifMetadata>): Promise<Array<GifMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GifMetadata_n11(uploadFile, downloadFile, x)));
}
function from_candid_vec_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScoreEntry>): Array<ScoreEntry> {
    return value.map((x)=>from_candid_ScoreEntry_n33(uploadFile, downloadFile, x));
}
async function to_candid_AvatarType_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvatarType): Promise<_AvatarType> {
    return await to_candid_variant_n15(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_GameMode_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): _GameMode {
    return to_candid_variant_n31(uploadFile, downloadFile, value);
}
async function to_candid_PuffinProfile_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PuffinProfile): Promise<_PuffinProfile> {
    return await to_candid_record_n41(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
async function to_candid_record_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    fileType: string;
}): Promise<{
    blob: _ExternalBlob;
    fileType: string;
}> {
    return {
        blob: await to_candid_ExternalBlob_n17(uploadFile, downloadFile, value.blob),
        fileType: value.fileType
    };
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n41(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    avatarType: AvatarType;
}): Promise<{
    bio: string;
    displayName: string;
    avatarType: _AvatarType;
}> {
    return {
        bio: value.bio,
        displayName: value.displayName,
        avatarType: await to_candid_AvatarType_n14(uploadFile, downloadFile, value.avatarType)
    };
}
async function to_candid_variant_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: {
        blob: ExternalBlob;
        fileType: string;
    };
} | {
    __kind__: "preset";
    preset: bigint;
}): Promise<{
    custom: {
        blob: _ExternalBlob;
        fileType: string;
    };
} | {
    preset: bigint;
}> {
    return value.__kind__ === "custom" ? {
        custom: await to_candid_record_n16(uploadFile, downloadFile, value.custom)
    } : value.__kind__ === "preset" ? {
        preset: value.preset
    } : value;
}
function to_candid_variant_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameMode): {
    flightAdventure: null;
} | {
    puffinSlide: null;
} | {
    puffinTowerDefense: null;
} | {
    fishFrenzy: null;
} | {
    puffinColonyWars: null;
} | {
    puffinRescue: null;
} | {
    arcticSurf: null;
} | {
    puffinCatch: null;
} {
    return value == GameMode.flightAdventure ? {
        flightAdventure: null
    } : value == GameMode.puffinSlide ? {
        puffinSlide: null
    } : value == GameMode.puffinTowerDefense ? {
        puffinTowerDefense: null
    } : value == GameMode.fishFrenzy ? {
        fishFrenzy: null
    } : value == GameMode.puffinColonyWars ? {
        puffinColonyWars: null
    } : value == GameMode.puffinRescue ? {
        puffinRescue: null
    } : value == GameMode.arcticSurf ? {
        arcticSurf: null
    } : value == GameMode.puffinCatch ? {
        puffinCatch: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
